### PR TITLE
Local Certificate Store lookup by FindType and FindValue

### PR DESCRIPTION
**Pull request by edinmilic**
Updating LocalStoreServerCertificateSource to supporting doing a more specific certificate search by allowing FindType and FindValue configuration

### CODE REVIEW

**Comment by mataness** [comment]
Can you also update the Kestrel.HttpsCertificateSelection.AzureKeyVault library version to 2.0.0 ? because this package depends on Kestrel.HttpsCertificateSelection

**Comment by mataness** [comment]
Why did you had to change so many files? it seem that the commits contains file that were changed, but their content is exactly the same. Any idea why ?

**Comment by edinmilic** [comment]
Updated the Kestrel.HttpsCertificateSelection.AzureKeyVault version, didn't see initially it had a dependency.
The reason files shows up in git as changed while the content is the same is because we used to have a single HelloWorld project in the samples folder. I added another one to be able to test both scenarios and when I did that I renamed the existing one but because it technically is a change (rename) github will show it in the diff tool

**Comment by mataness** [comment]
> Updated the Kestrel.HttpsCertificateSelection.AzureKeyVault version, didn't see initially it had a dependency. The reason files shows up in git as changed while the content is the same is because we used to have a single HelloWorld project in the samples folder. I added another one to be able to test both scenarios and when I did that I renamed the existing one but because it technically is a change (rename) github will show it in the diff tool

Thanks, just add the code comment as I asked in the other PR comment and push the commit, after that I'll merge the PR.

**Comment by edinmilic** [comment]
> > Updated the Kestrel.HttpsCertificateSelection.AzureKeyVault version, didn't see initially it had a dependency. The reason files shows up in git as changed while the content is the same is because we used to have a single HelloWorld project in the samples folder. I added another one to be able to test both scenarios and when I did that I renamed the existing one but because it technically is a change (rename) github will show it in the diff tool
> 
> Thanks, just add the code comment as I asked in the other PR comment and push the commit, after that I'll merge the PR.

Sorry, not sure what you mean by code comment? My previous commit has updated the code version of the kv library too

**Comment by mataness** [comment]
Never mind, merged.

**Pull request merged**
